server:
  port: 9010

spring:
  application:
    name: "message"
  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        #emailsms - binding name
        #in - indicates input binding
        #0 - starting index value
        #For getting message from message broker
        emailsms-in-0:
          #Any messages coming to queue, will be redirected to above function,destination(queue) random name
          destination: send-communication
          #When we specify group queue will not have randomly generated suffix value
          group: ${spring.application.name}
        #For publishing message in message broker
        emailsms-out-0:
          destination: communication-sent
      kafka:
        binder:
          brokers:
            - localhost:9092