spring:
  application:
    name: "eurekaserver"
  config:
    import:
      - application-qa.yml
      - application-prod.yml

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8070

eureka:
  instance:
    hostname: localhost
  client:
    #Don't fetch registry details of other microservices
    #In individual microservices this value must be set to default true
    fetchRegistry: false
    #We tell Eureka don't register yourself and don't expose your details
    #into the registry of the discovery service
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/