server:
  port: 8080
spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
  datasource:
#    url: jdbc:h2:mem:testDb
    url: jdbc:mysql://localhost:3306/accountsdb
#    driver-class-name: org.h2.Driver
    username: root
    password: root
#  h2:
#    console:
#      enabled: true
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
       include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    # By Default it will register via hostname, but it will make sense when we
    # want to use DNS mappings, but inside our local system we don't have any DNS
    # mapping set up, we should use preferIpAddress as true
    preferIpAddress: true
  client:
    # True to be sure that service fetch the registry details whenever trying
    # to connect with other microservices
    fetchRegistry: true
    # To allow our account service to register itself in eureka server
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "accounts"
    description: "Sergshamiryan Bank accounts Application"
    version: "1.0.0"