services:
  network-deploy-service:
    networks:
      - sergshamiryan

  microservice-db-config:
    extends:
      service: network-deploy-service
    image: mysql
    healthcheck: #Specifying for accounts service to wait accountsdb to be healthy before start
      test: [ "CMD","mysqladmin","ping","-h","localhost" ] #Commands can be found from official docs
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    depends_on:
      configServer:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default
      SPRING_RABBITMQ_HOST: "rabbit"