services:
  accountsdb:
    container_name: accountsdb
    ports:
      - 3310:3306
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  cardsdb:
    container_name: cardsdb
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  loansdb:
    container_name: loansdb
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  accounts:
    image: "sergshamriyan/accounts:latest"
    container_name: "accounts-ms"
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      #need to be 3306, because this is internal docker network
      #communication within docker containers
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "sergshamriyan/loans:latest"
    container_name: "loans-ms"
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_PROFILES_ACTIVE: default
      #need to be 3306, because this is internal docker network
      #communication within docker containers
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    depends_on:
      loansdb:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config

  cards:
    image: "sergshamriyan/cards:latest"
    container_name: "cards-ms"
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: cards
      SPRING_PROFILES_ACTIVE: default
      #need to be 3306, because this is internal docker network
      #communication within docker containers
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    depends_on:
      loansdb:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config

  configserver:
    image: "sergshamriyan/configserver:latest"
    container_name: "configserver-ms"
    ports:
      - 8071:8071
    #    depends_on:
    #      rabbit:
    #        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s #With timeout of 10 sec
      timeout: 5s #Inside each check don`t wait more than 5 sec
      retries: 10 #Retry 10 times
      start_period: 10s #After 10 sec
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "sergshamriyan/eurekaserver:latest"
    container_name: "eurekaserver-ms"
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s #With timeout of 10 sec
      timeout: 5s #Inside each check don`t wait more than 5 sec
      retries: 10 #Retry 10 times
      start_period: 10s #After 10 sec
    extends:
      file: common-config.yml
      service: microservice-nonDb-base-config
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: "eurekaserver"

  gatewayserver:
    image: "sergshamriyan/gatewayserver:latest"
    container_name: "gatewayserver-ms"
    ports:
      - "8072:8072"
    healthcheck:
      test: "curl --fail --silent localhost:8072/actuator/health/readiness | grep UP || exit 1"
      interval: 10s #With timeout of 10 sec
      timeout: 5s #Inside each check don`t wait more than 5 sec
      retries: 10 #Retry 10 times
      start_period: 10s #After 10 sec
    extends:
      file: common-config.yml
      service: microservice-nonDb-base-config-with-eureka
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: "gatewayserver"

networks:
  sergshamiryan:
    driver: "bridge"